# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Song.destroy_all

demo = User.create!(username: 'demo', email: 'demo@user.edu', password: 'demouser')
kygo = User.create!(username: 'Kygo', email: 'kygo@gmail.com', password: '123456')
illenium = User.create!(username: 'Illenium', email: 'illenium@gmail.com', password: '123456')
aku = User.create!(username: 'aKu', email: 'aku@gmail.com', password: '123456')
maggie = User.create!(username: 'Maggie Lindemann', email: 'maggie@gmail.com', password: '123456')
bkaye = User.create!(username: 'BKAYE', email: 'bkaye@gmail.com', password: '123456')
jpwp = User.create!(username: 'Japanese Wallpaper', email: 'jpwp@gmail.com', password: '123456')
rehab = User.create!(username: 'R3HAB', email: 'r3hab@gmail.com', password: '123456')
lostkings = User.create!(username: 'Lost Kings', email: 'lostkings@gmail.com', password: '123456')
codeko = User.create!(username: 'CODEKO', email: 'codeko@gmail.com', password: '123456')
yellowclaw = User.create!(username: 'Yellow Claw', email: 'yellowclaw@gmail.com', password: '123456')
shaunfrank = User.create!(username: 'Shaun Frank', email: 'shaunfrank@gmail.com', password: '123456')
youngbombs = User.create!(username: 'Young Bombs', email: 'youngbombs@gmail.com', password: '123456')
ss = User.create!(username: 'Sultan + Shepard', email: 'ss@gmail.com', password: '123456')
hibell = User.create!(username: 'Hibell', email: 'hibell@gmail.com', password: '123456')
marshmello = User.create!(username: 'Marshmello', email: 'marshmello@gmail.com', password: '123456')
edit = User.create!(username: 'edIT', email: 'edit@gmail.com', password: '123456')
xx = User.create!(username: 'The XX', email: 'xx@gmail.com', password: '123456')
krewella = User.create!(username: 'Krewella', email: 'krewella@gmail.com', password: '123456')
skrillex = User.create!(username: 'Skrillex', email: 'skrillex@gmail.com', password: '123456')
glitch = User.create!(username: 'The Gltich Mob', email: 'glitch@gmail.com', password: '123456')
the1975 = User.create!(username: 'The 1975', email: 'the1975@gmail.com', password: '123456')
theweeknd = User.create!(username: 'The Weeknd', email: 'theweeknd@gmail.com', password: '123456')
samsmith = User.create!(username: 'Sam Smith', email: 'samsmith@gmail.com', password: '123456')
edsheeran = User.create!(username: 'Ed Sheeran', email: 'edsheeran@gmail.com', password: '123456')

userfile1 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user1.jpg')
demo.profile_pic.attach(io: userfile1, filename: "img_#{demo.id}.jpg")
userfile2 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user2.png')
kygo.profile_pic.attach(io: userfile2, filename: "img_#{kygo.id}.png")
userfile3 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user3.png')
illenium.profile_pic.attach(io: userfile3, filename: "img_#{illenium.id}.png")
userfile4 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user4.png')
aku.profile_pic.attach(io: userfile4, filename: "img_#{aku.id}.png")
userfile5 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user5.png')
maggie.profile_pic.attach(io: userfile5, filename: "img_#{maggie.id}.png")
userfile6 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user6.png')
bkaye.profile_pic.attach(io: userfile6, filename: "img_#{bkaye.id}.png")
userfile7 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user7.png')
jpwp.profile_pic.attach(io: userfile7, filename: "img_#{jpwp.id}.png")
userfile8 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user8.png')
rehab.profile_pic.attach(io: userfile8, filename: "img_#{rehab.id}.png")
userfile9 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user9.png')
lostkings.profile_pic.attach(io: userfile9, filename: "img_#{lostkings.id}.png")
userfile10 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user10.png')
codeko.profile_pic.attach(io: userfile10, filename: "img_#{codeko.id}.png")
userfile11 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user11.png')
yellowclaw.profile_pic.attach(io: userfile11, filename: "img_#{yellowclaw.id}.png")
userfile12 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user12.png')
shaunfrank.profile_pic.attach(io: userfile12, filename: "img_#{shaunfrank.id}.png")
userfile13 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user13.png')
youngbombs.profile_pic.attach(io: userfile13, filename: "img_#{youngbombs.id}.png")
userfile14 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user14.png')
ss.profile_pic.attach(io: userfile14, filename: "img_#{ss.id}.png")
userfile15 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user15.png')
hibell.profile_pic.attach(io: userfile15, filename: "img_#{hibell.id}.png")
userfile16 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user16.png')
marshmello.profile_pic.attach(io: userfile16, filename: "img_#{marshmello.id}.png")
userfile17 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user17.png')
edit.profile_pic.attach(io: userfile17, filename: "img_#{edit.id}.png")
userfile18 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user18.png')
xx.profile_pic.attach(io: userfile18, filename: "img_#{xx.id}.png")
userfile19 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user19.png')
krewella.profile_pic.attach(io: userfile19, filename: "img_#{krewella.id}.png")
userfile20 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user20.png')
skrillex.profile_pic.attach(io: userfile20, filename: "img_#{skrillex.id}.png")
userfile21 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user21.png')
glitch.profile_pic.attach(io: userfile21, filename: "img_#{glitch.id}.png")
userfile22 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user22.png')
the1975.profile_pic.attach(io: userfile22, filename: "img_#{the1975.id}.png")
userfile23 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user23.png')
theweeknd.profile_pic.attach(io: userfile23, filename: "img_#{theweeknd.id}.png")
userfile24 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user24.png')
samsmith.profile_pic.attach(io: userfile24, filename: "img_#{samsmith.id}.png")
userfile25 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/user25.png')
edsheeran.profile_pic.attach(io: userfile25, filename: "img_#{edsheeran.id}.png")

song1 = Song.create!(title: 'I See Fire by Ed Sheeran(Kygo Remix)', artist_id: kygo.id, genre: 'House', description: 'Fire 🔥🔥🔥')
song2 = Song.create!(title: 'Miami 82 by Syn Cole (Kygo Remix)', artist_id: kygo.id, genre: 'House', description: 'Sunshine on my mind')
song3 = Song.create!(title: 'Can’t Afford It All by Jakubi (Kygo Remix)', artist_id: kygo.id, genre: 'House', description: 'Born to shop. Forced to work')
song4 = Song.create!(title: 'Shark by Oh Wonder (Illenium Remix)', artist_id: illenium.id, genre: 'Pop', description: 'Shark week every week')
song5 = Song.create!(title: 'The Final Blow', artist_id: aku.id, genre: 'Electronic', description: 'Cherry blossom dreaming')
song6 = Song.create!(title: 'Pretty Girl', artist_id: maggie.id, genre: 'Pop', description: 'Perfect imperfection')
song7 = Song.create!(title: 'Nightlight', artist_id: illenium.id, genre: 'Pop', description: 'The night is darkest before the dawn')
song8 = Song.create!(title: 'Be Together by Major Lazer (BKAYE Remix)', artist_id: bkaye.id, genre: 'DanceEDM', description: 'Sunny rays and festival days')
song9 = Song.create!(title: 'Piñata by Montgomery (Japanese Wallpaper Remix)', artist_id: jpwp.id, genre: 'Pop', description: 'Happy birthday to the ground')
song10 = Song.create!(title: 'Ain’t My Fault by Zara Larsson (R3HAB Remix)', artist_id: rehab.id, genre: 'DanceEDM', description: 'I know guac is extra but so am I')
song11 = Song.create!(title: 'Ghost by Halsey (Lost Kings Remix)', artist_id: lostkings.id, genre: 'Pop', description: 'Boo-tiful')
song12 = Song.create!(title: 'Walking with Lions ft. Raphaella', artist_id: codeko.id, genre: 'DanceEDM', description: 'Hakuna Matata')
song13 = Song.create!(title: 'Love & War', artist_id: yellowclaw.id, genre: 'DanceEDM', description: 'Save the last White Claw for me')
song14 = Song.create!(title: 'Tokyo Nights', artist_id: shaunfrank.id, genre: 'Electronic', description: 'Greetings from Japan')
song15 = Song.create!(title: 'The Cure by Lady Gaga (Young Bombs Remix)', artist_id: youngbombs.id, genre: 'Pop', description: 'Spoonful of Sugar')
song16 = Song.create!(title: 'Lay It All On Me by Rudimental ft. Ed Sheeran (Sultan + Shepard Remix)', artist_id: ss.id, genre: 'Pop', description: 'Rudimental')
song17 = Song.create!(title: 'Icarus (Skytech Remix)', artist_id: rehab.id, genre: 'DanceEDM', description: 'Head in the Clouds')
song18 = Song.create!(title: 'Perfect Places by Lorde (Hibell Remix)', artist_id: hibell.id, genre: 'Pop', description: 'Smoke and Sunset')
song19 = Song.create!(title: 'Keep It Mello ft. Omar LinX', artist_id: marshmello.id, genre: 'House', description: 'Chubby Bunny')
song20 = Song.create!(title: 'Straight Heat', artist_id: edit.id, genre: 'Electronic', description: 'Certified Air Raid Material')
song21 = Song.create!(title: 'Intro', artist_id: xx.id, genre: 'Electronic', description: 'Dun Dun Clap')
song22 = Song.create!(title: 'Surrender the Throne', artist_id: krewella.id, genre: 'Electronic', description: 'Winter is Coming')
song23 = Song.create!(title: 'Drunk Me by Mitchell Tenpenny (R3HAB Remix)', artist_id: rehab.id, genre: 'DanceEDM', description: '100 Proof')
song24 = Song.create!(title: 'Disarm You by Kaskade ft. Ilsey (Illenium Remix)', artist_id: illenium.id, genre: 'DanceEDM', description: 'Let Me Disarm You')
song25 = Song.create!(title: 'Mine by Phoebe Ryan (Illenium Remix)', artist_id: illenium.id, genre: 'Electronic', description: 'Be Mine ❤️❤️❤️')
song26 = Song.create!(title: 'Fractures ft. Nevve', artist_id: illenium.id, genre: 'DanceEDM', description: 'Shatter and Collide')
song27 = Song.create!(title: 'Cut Your Teeth by Kyla La Grange (Kygo Remix)', artist_id: kygo.id, genre: 'House', description: 'You Cut Your Teeth on the Lack of Answers')
song28 = Song.create!(title: 'Sexual Healing by Marvin Gaye (Kygo Remix)', artist_id: kygo.id, genre: 'House', description: 'Soulful')
song29 = Song.create!(title: 'Messy by Kiarra (R3HAB Remix)', artist_id: rehab.id, genre: 'Pop', description: 'Let`s Stop Before It Gets Messy')
song30 = Song.create!(title: 'Symphony by Clean Bandit & Zara Larsson (R3HAB Remix)', artist_id: rehab.id, genre: 'DanceEDM', description: 'Rhapsody for You and Me')
song31 = Song.create!(title: 'Quit You ft. Tinashe', artist_id: lostkings.id, genre: 'DanceEDM', description: 'I Can`t Quit You')
song32 = Song.create!(title: 'Overdrive by Oliver Heldens (Lost Kings Remix)', artist_id: lostkings.id, genre: 'DanceEDM', description: 'Got My Heart on Overdrive')
song33 = Song.create!(title: 'Phone Down ft. Emily Warren', artist_id: lostkings.id, genre: 'Pop', description: 'Why Don`t You Put That F&%king Phone Down?')
song34 = Song.create!(title: 'Alone', artist_id: marshmello.id, genre: 'Electronic', description: 'Trying to Find My Way Back Home To You')
song35 = Song.create!(title: 'Come and Get It (Razihel Remix)', artist_id: krewella.id, genre: 'Dubstep', description: 'Tear Me Apart and Watch It Burn')
song36 = Song.create!(title: 'Live For The Night', artist_id: krewella.id, genre: 'Dubstep', description: 'Krewella Krew')
song37 = Song.create!(title: 'Alibi', artist_id: krewella.id, genre: 'Electronic', description: 'Stay With Me Tonight, I`ll Be Your Alibi')
song38 = Song.create!(title: 'Bangarang', artist_id: skrillex.id, genre: 'Dubstep', description: 'Turn Up the Bass')
song39 = Song.create!(title: 'Fortune Days', artist_id: glitch.id, genre: 'Electronic', description: 'Running Out of Luck')
song40 = Song.create!(title: 'Animus Vox', artist_id: glitch.id, genre: 'Electronic', description: 'Drink The Sea')
song41 = Song.create!(title: 'Our Demons ft. Aja Volkman', artist_id: glitch.id, genre: 'Electronic', description: 'Demon Within')
song42 = Song.create!(title: 'Rise', artist_id: glitch.id, genre: 'Alternative Rock', description: 'League of Legends')
song43 = Song.create!(title: 'TOOTIMETOOTIMETOOTIME', artist_id: the1975.id, genre: 'Alternative Rock', description: 'Two Timer')
song44 = Song.create!(title: 'It`s Not Living (If It`s Not With You)', artist_id: the1975.id, genre: 'Alternative Rock', description: 'All I Need')
song45 = Song.create!(title: 'Sincerity is Scary', artist_id: the1975.id, genre: 'Alternative Rock', description: 'Why Must It Be So Complicated?')
song46 = Song.create!(title: 'Somebody Else', artist_id: the1975.id, genre: 'Alternative Rock', description: 'Picturing You With Somebody Else')
song47 = Song.create!(title: 'Menswear', artist_id: the1975.id, genre: 'Alternative Rock', description: 'Dressed In White')
song48 = Song.create!(title: 'Blinding Lights', artist_id: theweeknd.id, genre: 'RBSoul', description: 'I`m Blinded by the Lights')
song49 = Song.create!(title: 'I Feel It Coming (ft. Daft Punk)', artist_id: theweeknd.id, genre: 'RBSoul', description: 'I Feel It Coming Babe')
song50 = Song.create!(title: 'Starboy (ft. Daft Punk)', artist_id: theweeknd.id, genre: 'RBSoul', description: 'Cut That Ivory')
song51 = Song.create!(title: 'Attention', artist_id: theweeknd.id, genre: 'RBSoul', description: 'You`re Only Looking For Attention')
song52 = Song.create!(title: 'The Hills', artist_id: theweeknd.id, genre: 'RBSoul', description: 'I Only Call You When It`s Half Past Five')
song53 = Song.create!(title: 'Wicked Games', artist_id: theweeknd.id, genre: 'RBSoul', description: 'Playing These Wicked Games')
song54 = Song.create!(title: 'True Colors', artist_id: theweeknd.id, genre: 'RBSoul', description: 'Paint Me a Picture with Your True Colors')
song55 = Song.create!(title: 'Earned It', artist_id: theweeknd.id, genre: 'RBSoul', description: 'Fifty Shades of Grey')
song56 = Song.create!(title: 'La La La by Naughty Boy', artist_id: samsmith.id, genre: 'Pop', description: 'When Your Words Mean Nothing, I Go La La La')
song57 = Song.create!(title: 'Latch by Disclosure', artist_id: samsmith.id, genre: 'Pop', description: 'I`m Latching Onto You')
song58 = Song.create!(title: 'Diamonds', artist_id: samsmith.id, genre: 'Pop', description: 'Platinum and Gold')
song59 = Song.create!(title: 'I`m Ready ft. Demi Lovato', artist_id: samsmith.id, genre: 'Pop', description: 'Ready For Someone to Love Me')
song60 = Song.create!(title: 'I Don`t Care (with Justin Bieber)', artist_id: edsheeran.id, genre: 'Pop', description: 'I Don`t Care, As Long As You Just Hold Me Near')
song61 = Song.create!(title: 'Put It All On Me ft. Ella Mai', artist_id: edsheeran.id, genre: 'Pop', description: 'Put Your Worries On Me')
song62 = Song.create!(title: 'Beautiful People ft. Khalid', artist_id: edsheeran.id, genre: 'Pop', description: 'Sundown in L.A.')
song63 = Song.create!(title: 'South of the Border ft. Camila Cabella & Cardi B', artist_id: edsheeran.id, genre: 'Pop', description: 'Come South of the Border With Me')

songImg1 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/1.png')
song1.imageURL.attach(io: songImg1, filename: "song#{song1.id}_img.png")
songAud1 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/1.+I+See+Fire+(Kygo+Remix).mp3')
song1.audioURL.attach(io: songAud1, filename: "song#{song1.id}_aud.mp3")

songImg2 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/2.png')
song2.imageURL.attach(io: songImg2, filename: "song#{song2.id}_img.png")
songAud2 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/2.+Miami+82+(Kygo+Remix).mp3')
song2.audioURL.attach(io: songAud2, filename: "song#{song2.id}_aud.mp3")

songImg3 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/3.png')
song3.imageURL.attach(io: songImg3, filename: "song#{song3.id}_img.png")
songAud3 = open("https://soundcrowd-seed.s3-us-west-1.amazonaws.com/3.+Jakubi+-+Can't+Afford+It+All+(Kygo+Remix).mp3")
song3.audioURL.attach(io: songAud3, filename: "song#{song3.id}_aud.mp3")

songImg4 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/4.png')
song4.imageURL.attach(io: songImg4, filename: "song#{song4.id}_img.png")
songAud4 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/4.+Oh+Wonder+-+Shark+(Illenium+Remix).mp3')
song4.audioURL.attach(io: songAud4, filename: "song#{song4.id}_aud.png")

songImg5 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/5.png')
song5.imageURL.attach(io: songImg5, filename: "song#{song5.id}_img.png")
songAud5 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/5.+aKu+-+The+Final+Blow.mp3')
song5.audioURL.attach(io: songAud5, filename: "song#{song5.id}_aud.png")

songImg6 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/6.png')
song6.imageURL.attach(io: songImg6, filename: "song#{song6.id}_img.png")
songAud6 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/6.+Pretty+Girl.mp3')
song6.audioURL.attach(io: songAud6, filename: "song#{song6.id}_aud.mp3")

songImg7 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/7.png')
song7.imageURL.attach(io: songImg7, filename: "song#{song7.id}_img.png")
songAud7 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/7.+Nightlight.mp3')
song7.audioURL.attach(io: songAud7, filename: "song#{song7.id}_aud.mp3")

songImg8 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/8.png')
song8.imageURL.attach(io: songImg8, filename: "song#{song8.id}_img.png")
songAud8 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/8.+Major+Lazer+ft.+Wild+Belle+-+Be+Together+(BKAYE+Remix).mp3')
song8.audioURL.attach(io: songAud8, filename: "song#{song8.id}_aud.mp3")

songImg9 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/9.png')
song9.imageURL.attach(io: songImg9, filename: "song#{song9.id}_img.png")
songAud9 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/9.+Montgomery+-+Pinata+(Japanese+Wallpaper+Remix).mp3')
song9.audioURL.attach(io: songAud9, filename: "song#{song9.id}_aud.mp3")

songImg10 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/10.png')
song10.imageURL.attach(io: songImg10, filename: "song#{song10.id}_img.png")
songAud10 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/10.+Zara+Larsson+-+Aint+My+Fault+(R3hab+Remix).mp3')
song10.audioURL.attach(io: songAud10, filename: "song#{song10.id}_aud.mp3")

songImg11 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/11.png')
song11.imageURL.attach(io: songImg11, filename: "song#{song11.id}_img.png")
songAud11 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/11.+Halsey+-+Ghost+(Lost+Kings+Remix).mp3')
song11.audioURL.attach(io: songAud11, filename: "song#{song11.id}_aud.mp3")

songImg12 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/12.png')
song12.imageURL.attach(io: songImg12, filename: "song#{song12.id}_img.png")
songAud12 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/12.+CODEKO+feat.+Raphaella+-+Walking+With+Lions+(Official+Electric+Zoo+Anthem).mp3')
song12.audioURL.attach(io: songAud12, filename: "song#{song12.id}_aud.mp3")

songImg13 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/13.png')
song13.imageURL.attach(io: songImg13, filename: "song#{song13.id}_img.png")
songAud13 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/13.+Yellow+Claw+-+Love+%26+War+ft.+Yade+Lauren+(OUT+NOW).mp3')
song13.audioURL.attach(io: songAud13, filename: "song#{song13.id}_aud.mp3")

songImg14 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/14.png')
song14.imageURL.attach(io: songImg14, filename: "song#{song14.id}_img.png")
songAud14 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/14.+Shaun+Frank+-+Tokyo+Nights.mp3')
song14.audioURL.attach(io: songAud14, filename: "song#{song14.id}_aud.mp3")

songImg15 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/15.png')
song15.imageURL.attach(io: songImg15, filename: "song#{song15.id}_img.png")
songAud15 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/15.+Lady_Gaga+-+The+Cure+(Young+Bombs+Remix).mp3')
song15.audioURL.attach(io: songAud15, filename: "song#{song15.id}_aud.mp3")

songImg16 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/16.png')
song16.imageURL.attach(io: songImg16, filename: "song#{song16.id}_img.png")
songAud16 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/16.+Rudimental+-+Lay+It+All+On+Me+%5BSultan+%2B+Shepard+Remix%5D.mp3')
song16.audioURL.attach(io: songAud16, filename: "song#{song16.id}_aud.mp3")

songImg17 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/17.png')
song17.imageURL.attach(io: songImg17, filename: "song#{song17.id}_img.png")
songAud17 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/17.+R3hab+-+Icarus+(R3hab+%26+Skytech+Remix).mp3')
song17.audioURL.attach(io: songAud17, filename: "song#{song17.id}_aud.mp3")

songImg18 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/18.png')
song18.imageURL.attach(io: songImg18, filename: "song#{song18.id}_img.png")
songAud18 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/18.+Lorde+-+Perfect+Places+(Hibell+Remix).mp3')
song18.audioURL.attach(io: songAud18, filename: "song#{song18.id}_aud.mp3")

songImg19 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/19.png')
song19.imageURL.attach(io: songImg19, filename: "song#{song19.id}_img.png")
songAud19 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/19.+KeEp+IT+MeLLo+Feat.+Omar+LinX.mp3')
song19.audioURL.attach(io: songAud19, filename: "song#{song19.id}_aud.mp3")

songImg20 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/20.png')
song20.imageURL.attach(io: songImg20, filename: "song#{song20.id}_img.png")
songAud20 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/20.+Straight+Heat.mp3')
song20.audioURL.attach(io: songAud20, filename: "song#{song20.id}_aud.mp3")

songImg21 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/21.png')
song21.imageURL.attach(io: songImg21, filename: "song#{song21.id}_img.png")
songAud21 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/21.mp3')
song21.audioURL.attach(io: songAud21, filename: "song#{song21.id}_aud.mp3")

songImg22 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/22.png')
song22.imageURL.attach(io: songImg22, filename: "song#{song22.id}_img.png")
songAud22 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/22.mp3')
song22.audioURL.attach(io: songAud22, filename: "song#{song22.id}_aud.mp3")

songImg23 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/23.png')
song23.imageURL.attach(io: songImg23, filename: "song#{song23.id}_img.png")
songAud23 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/23.mp3')
song23.audioURL.attach(io: songAud23, filename: "song#{song23.id}_aud.mp3")

songImg24 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/24.png')
song24.imageURL.attach(io: songImg24, filename: "song#{song24.id}_img.png")
songAud24 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/24.mp3')
song24.audioURL.attach(io: songAud24, filename: "song#{song24.id}_aud.mp3")

songImg25 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/25.png')
song25.imageURL.attach(io: songImg25, filename: "song#{song25.id}_img.png")
songAud25 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/25.mp3')
song25.audioURL.attach(io: songAud25, filename: "song#{song25.id}_aud.mp3")

songImg26 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/26.png')
song26.imageURL.attach(io: songImg26, filename: "song#{song26.id}_img.png")
songAud26 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/26.mp3')
song26.audioURL.attach(io: songAud26, filename: "song#{song26.id}_aud.mp3")

songImg27 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/27.png')
song27.imageURL.attach(io: songImg27, filename: "song#{song27.id}_img.png")
songAud27 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/27.mp3')
song27.audioURL.attach(io: songAud27, filename: "song#{song27.id}_aud.mp3")

songImg28 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/28.png')
song28.imageURL.attach(io: songImg28, filename: "song#{song28.id}_img.png")
songAud28 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/28.mp3')
song28.audioURL.attach(io: songAud28, filename: "song#{song28.id}_aud.mp3")

songImg29 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/29.png')
song29.imageURL.attach(io: songImg29, filename: "song#{song29.id}_img.png")
songAud29 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/29.mp3')
song29.audioURL.attach(io: songAud29, filename: "song#{song29.id}_aud.mp3")

songImg30 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/30.png')
song30.imageURL.attach(io: songImg30, filename: "song#{song30.id}_img.png")
songAud30 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/30.mp3')
song30.audioURL.attach(io: songAud30, filename: "song#{song30.id}_aud.mp3")

songImg31 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/31.png')
song31.imageURL.attach(io: songImg31, filename: "song#{song31.id}_img.png")
songAud31 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/31.mp3')
song31.audioURL.attach(io: songAud31, filename: "song#{song31.id}_aud.mp3")

songImg32 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/32.png')
song32.imageURL.attach(io: songImg32, filename: "song#{song32.id}_img.png")
songAud32 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/32.mp3')
song32.audioURL.attach(io: songAud32, filename: "song#{song32.id}_aud.mp3")

songImg33 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/33.png')
song33.imageURL.attach(io: songImg33, filename: "song#{song33.id}_img.png")
songAud33 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/33.mp3')
song33.audioURL.attach(io: songAud33, filename: "song#{song33.id}_aud.mp3")

songImg34 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/34.png')
song34.imageURL.attach(io: songImg34, filename: "song#{song34.id}_img.png")
songAud34 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/34.mp3')
song34.audioURL.attach(io: songAud34, filename: "song#{song34.id}_aud.mp3")

songImg35 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/35.png')
song35.imageURL.attach(io: songImg35, filename: "song#{song35.id}_img.png")
songAud35 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/35.mp3')
song35.audioURL.attach(io: songAud35, filename: "song#{song35.id}_aud.mp3")

songImg36 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/36.png')
song36.imageURL.attach(io: songImg36, filename: "song#{song36.id}_img.png")
songAud36 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/36.mp3')
song36.audioURL.attach(io: songAud36, filename: "song#{song36.id}_aud.mp3")

songImg37 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/37.png')
song37.imageURL.attach(io: songImg37, filename: "song#{song37.id}_img.png")
songAud37 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/37.mp3')
song37.audioURL.attach(io: songAud37, filename: "song#{song37.id}_aud.mp3")

songImg38 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/38.png')
song38.imageURL.attach(io: songImg38, filename: "song#{song38.id}_img.png")
songAud38 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/38.mp3')
song38.audioURL.attach(io: songAud38, filename: "song#{song38.id}_aud.mp3")

songImg39 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/39.png')
song39.imageURL.attach(io: songImg39, filename: "song#{song39.id}_img.png")
songAud39 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/39.mp3')
song39.audioURL.attach(io: songAud39, filename: "song#{song39.id}_aud.mp3")

songImg40 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/40.png')
song40.imageURL.attach(io: songImg40, filename: "song#{song40.id}_img.png")
songAud40 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/40.mp3')
song40.audioURL.attach(io: songAud40, filename: "song#{song40.id}_aud.mp3")

songImg41 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/41.png')
song41.imageURL.attach(io: songImg41, filename: "song#{song41.id}_img.png")
songAud41 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/41.mp3')
song41.audioURL.attach(io: songAud41, filename: "song#{song41.id}_aud.mp3")

songImg42 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/42.png')
song42.imageURL.attach(io: songImg42, filename: "song#{song42.id}_img.png")
songAud42 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/42.mp3')
song42.audioURL.attach(io: songAud42, filename: "song#{song42.id}_aud.mp3")

songImg43 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/43.png')
song43.imageURL.attach(io: songImg43, filename: "song#{song43.id}_img.png")
songAud43 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/43.mp3')
song43.audioURL.attach(io: songAud43, filename: "song#{song43.id}_aud.mp3")

songImg44 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/44.png')
song44.imageURL.attach(io: songImg44, filename: "song#{song44.id}_img.png")
songAud44 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/44.mp3')
song44.audioURL.attach(io: songAud44, filename: "song#{song44.id}_aud.mp3")

songImg45 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/45.png')
song45.imageURL.attach(io: songImg45, filename: "song#{song45.id}_img.png")
songAud45 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/45.mp3')
song45.audioURL.attach(io: songAud45, filename: "song#{song45.id}_aud.mp3")

songImg46 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/46.png')
song46.imageURL.attach(io: songImg46, filename: "song#{song46.id}_img.png")
songAud46 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/46.mp3')
song46.audioURL.attach(io: songAud46, filename: "song#{song46.id}_aud.mp3")

songImg47 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/47.png')
song47.imageURL.attach(io: songImg47, filename: "song#{song47.id}_img.png")
songAud47 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/47.mp3')
song47.audioURL.attach(io: songAud47, filename: "song#{song47.id}_aud.mp3")

songImg48 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/48.png')
song48.imageURL.attach(io: songImg48, filename: "song#{song48.id}_img.png")
songAud48 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/48.mp3')
song48.audioURL.attach(io: songAud48, filename: "song#{song48.id}_aud.mp3")

songImg49 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/49.png')
song49.imageURL.attach(io: songImg49, filename: "song#{song49.id}_img.png")
songAud49 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/49.mp3')
song49.audioURL.attach(io: songAud49, filename: "song#{song49.id}_aud.mp3")

songImg50 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/50.png')
song50.imageURL.attach(io: songImg50, filename: "song#{song50.id}_img.png")
songAud50 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/50.mp3')
song50.audioURL.attach(io: songAud50, filename: "song#{song50.id}_aud.mp3")

songImg51 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/51.png')
song51.imageURL.attach(io: songImg51, filename: "song#{song51.id}_img.png")
songAud51 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/51.mp3')
song51.audioURL.attach(io: songAud51, filename: "song#{song51.id}_aud.mp3")

songImg52 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/52.png')
song52.imageURL.attach(io: songImg52, filename: "song#{song52.id}_img.png")
songAud52 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/52.mp3')
song52.audioURL.attach(io: songAud52, filename: "song#{song52.id}_aud.mp3")

songImg53 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/53.png')
song53.imageURL.attach(io: songImg53, filename: "song#{song53.id}_img.png")
songAud53 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/53.mp3')
song53.audioURL.attach(io: songAud53, filename: "song#{song53.id}_aud.mp3")

songImg54 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/54.png')
song54.imageURL.attach(io: songImg54, filename: "song#{song54.id}_img.png")
songAud54 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/54.mp3')
song54.audioURL.attach(io: songAud54, filename: "song#{song54.id}_aud.mp3")

songImg55 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/55.png')
song55.imageURL.attach(io: songImg55, filename: "song#{song55.id}_img.png")
songAud55 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/55.mp3')
song55.audioURL.attach(io: songAud55, filename: "song#{song55.id}_aud.mp3")

songImg56 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/56.png')
song56.imageURL.attach(io: songImg56, filename: "song#{song56.id}_img.png")
songAud56 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/56.mp3')
song56.audioURL.attach(io: songAud56, filename: "song#{song56.id}_aud.mp3")

songImg57 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/57.png')
song57.imageURL.attach(io: songImg57, filename: "song#{song57.id}_img.png")
songAud57 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/57.mp3')
song57.audioURL.attach(io: songAud57, filename: "song#{song57.id}_aud.mp3")

songImg58 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/58.png')
song58.imageURL.attach(io: songImg58, filename: "song#{song58.id}_img.png")
songAud58 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/58.mp3')
song58.audioURL.attach(io: songAud58, filename: "song#{song58.id}_aud.mp3")

songImg59 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/59.png')
song59.imageURL.attach(io: songImg59, filename: "song#{song59.id}_img.png")
songAud59 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/59.mp3')
song59.audioURL.attach(io: songAud59, filename: "song#{song59.id}_aud.mp3")

songImg60 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/60.png')
song60.imageURL.attach(io: songImg60, filename: "song#{song60.id}_img.png")
songAud60 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/60.mp3')
song60.audioURL.attach(io: songAud60, filename: "song#{song60.id}_aud.mp3")

songImg61 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/61.png')
song61.imageURL.attach(io: songImg61, filename: "song#{song61.id}_img.png")
songAud61 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/61.mp3')
song61.audioURL.attach(io: songAud61, filename: "song#{song61.id}_aud.mp3")

songImg62 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/62.png')
song62.imageURL.attach(io: songImg62, filename: "song#{song62.id}_img.png")
songAud62 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/62.mp3')
song62.audioURL.attach(io: songAud62, filename: "song#{song62.id}_aud.mp3")

songImg63 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/63.png')
song63.imageURL.attach(io: songImg63, filename: "song#{song63.id}_img.png")
songAud63 = open('https://soundcrowd-seed.s3-us-west-1.amazonaws.com/63.mp3')
song63.audioURL.attach(io: songAud63, filename: "song#{song63.id}_aud.mp3")

comment1 = Comment.create!(body: 'wow', song_id: song1.id, author_id: demo.id)
comment2 = Comment.create!(body: 'yay', song_id: song1.id, author_id: kygo.id)
comment3 = Comment.create!(body: 'sounds amazing', song_id: song1.id, author_id: illenium.id)
comment4 = Comment.create!(body: 'sign up for my MLM plox', song_id: song1.id, author_id: ss.id)
comment5 = Comment.create!(body: 'i remember this song from LOTR', song_id: song1.id, author_id: maggie.id)

comment6 = Comment.create!(body: 'kygo is the best', song_id: song2.id, author_id: marshmello.id)
comment7 = Comment.create!(body: 'omg omg', song_id: song2.id, author_id: yellowclaw.id)
comment8 = Comment.create!(body: 'i remember this coachella!!', song_id: song2.id, author_id: xx.id)
comment9 = Comment.create!(body: 'so tropical', song_id: song2.id, author_id: edsheeran.id)
comment10 = Comment.create!(body: 'when are you going on tour?', song_id: song2.id, author_id: samsmith.id)

comment11 = Comment.create!(body: 'can`t stop listening', song_id: song3.id, author_id: skrillex.id)
comment12 = Comment.create!(body: 'blasting this while driving', song_id: song3.id, author_id: krewella.id)
comment13 = Comment.create!(body: 'too good', song_id: song3.id, author_id: glitch.id)
comment14 = Comment.create!(body: 'summer vibes', song_id: song3.id, author_id: theweeknd.id)
comment15 = Comment.create!(body: 'adding to my playlist', song_id: song3.id, author_id: the1975.id)

comment16 = Comment.create!(body: 'repeat x100', song_id: song4.id, author_id: rehab.id)
comment17 = Comment.create!(body: 'so hype', song_id: song4.id, author_id: jpwp.id)
comment18 = Comment.create!(body: 'you`re the best!!', song_id: song4.id, author_id: edit.id)
comment19 = Comment.create!(body: 'so excited for this song', song_id: song4.id, author_id: edsheeran.id)
comment20 = Comment.create!(body: '~please come to Japan~ (>O_O)>', song_id: song4.id, author_id: bkaye.id)

comment21 = Comment.create!(body: 'can`t stop listening', song_id: song5.id, author_id: rehab.id)
comment22 = Comment.create!(body: 'blasting this while driving', song_id: song5.id, author_id: aku.id)
comment23 = Comment.create!(body: 'too good', song_id: song5.id, author_id: kygo.id)
comment24 = Comment.create!(body: 'summer vibes', song_id: song5.id, author_id: bkaye.id)
comment25 = Comment.create!(body: 'adding to my playlist', song_id: song5.id, author_id: the1975.id)

comment26 = Comment.create!(body: 'repeat x100', song_id: song6.id, author_id: aku.id)
comment27 = Comment.create!(body: 'so hype', song_id: song6.id, author_id: maggie.id)
comment28 = Comment.create!(body: 'you`re the best!!', song_id: song6.id, author_id: youngbombs.id)
comment29 = Comment.create!(body: 'so excited for this song', song_id: song6.id, author_id: ss.id)
comment30 = Comment.create!(body: 'please go on tour in Europe', song_id: song6.id, author_id: kygo.id)

comment31 = Comment.create!(body: 'can`t stop listening', song_id: song7.id, author_id: rehab.id)
comment32 = Comment.create!(body: 'blasting this while driving', song_id: song7.id, author_id: aku.id)
comment33 = Comment.create!(body: 'too good', song_id: song7.id, author_id: kygo.id)
comment34 = Comment.create!(body: 'summer vibes', song_id: song7.id, author_id: bkaye.id)
comment35 = Comment.create!(body: 'adding to my playlist', song_id: song7.id, author_id: the1975.id)

comment36 = Comment.create!(body: 'repeat x100', song_id: song8.id, author_id: aku.id)
comment37 = Comment.create!(body: 'so hype', song_id: song8.id, author_id: maggie.id)
comment38 = Comment.create!(body: 'you`re the best!!', song_id: song8.id, author_id: youngbombs.id)
comment39 = Comment.create!(body: 'so excited for this song', song_id: song8.id, author_id: ss.id)
comment40 = Comment.create!(body: 'please go on tour in Europe', song_id: song8.id, author_id: kygo.id)

comment41 = Comment.create!(body: 'can`t stop listening', song_id: song9.id, author_id: rehab.id)
comment42 = Comment.create!(body: 'blasting this while driving', song_id: song9.id, author_id: aku.id)
comment43 = Comment.create!(body: 'too good', song_id: song9.id, author_id: kygo.id)
comment44 = Comment.create!(body: 'summer vibes', song_id: song9.id, author_id: bkaye.id)
comment45 = Comment.create!(body: 'adding to my playlist', song_id: song9.id, author_id: the1975.id)

comment46 = Comment.create!(body: 'repeat x100', song_id: song10.id, author_id: aku.id)
comment47 = Comment.create!(body: 'so hype', song_id: song10.id, author_id: maggie.id)
comment48 = Comment.create!(body: 'you`re the best!!', song_id: song10.id, author_id: youngbombs.id)
comment49 = Comment.create!(body: 'so excited for this song', song_id: song10.id, author_id: ss.id)
comment50 = Comment.create!(body: 'please go on tour in Europe', song_id: song10.id, author_id: kygo.id)

comment51 = Comment.create!(body: 'can`t stop listening', song_id: song11.id, author_id: rehab.id)
comment52 = Comment.create!(body: 'blasting this while driving', song_id: song11.id, author_id: aku.id)
comment53 = Comment.create!(body: 'too good', song_id: song11.id, author_id: kygo.id)
comment54 = Comment.create!(body: 'summer vibes', song_id: song11.id, author_id: bkaye.id)
comment55 = Comment.create!(body: 'adding to my playlist', song_id: song11.id, author_id: the1975.id)

comment56 = Comment.create!(body: 'repeat x100', song_id: song12.id, author_id: aku.id)
comment57 = Comment.create!(body: 'so hype', song_id: song12.id, author_id: maggie.id)
comment58 = Comment.create!(body: 'you`re the best!!', song_id: song12.id, author_id: youngbombs.id)
comment59 = Comment.create!(body: 'so excited for this song', song_id: song12.id, author_id: ss.id)
comment60 = Comment.create!(body: 'please go on tour in Europe', song_id: song12.id, author_id: kygo.id)

comment61 = Comment.create!(body: 'can`t stop listening', song_id: song13.id, author_id: rehab.id)
comment62 = Comment.create!(body: 'blasting this while driving', song_id: song13.id, author_id: aku.id)
comment63 = Comment.create!(body: 'too good', song_id: song13.id, author_id: kygo.id)
comment64 = Comment.create!(body: 'summer vibes', song_id: song13.id, author_id: bkaye.id)
comment65 = Comment.create!(body: 'adding to my playlist', song_id: song13.id, author_id: the1975.id)

comment66 = Comment.create!(body: 'repeat x100', song_id: song14.id, author_id: aku.id)
comment67 = Comment.create!(body: 'so hype', song_id: song14.id, author_id: maggie.id)
comment68 = Comment.create!(body: 'you`re the best!!', song_id: song14.id, author_id: youngbombs.id)
comment69 = Comment.create!(body: 'so excited for this song', song_id: song14.id, author_id: ss.id)
comment70 = Comment.create!(body: 'please go on tour in Europe', song_id: song14.id, author_id: kygo.id)

comment71 = Comment.create!(body: 'can`t stop listening', song_id: song15.id, author_id: rehab.id)
comment72 = Comment.create!(body: 'blasting this while driving', song_id: song15.id, author_id: aku.id)
comment73 = Comment.create!(body: 'too good', song_id: song15.id, author_id: kygo.id)
comment74 = Comment.create!(body: 'summer vibes', song_id: song15.id, author_id: bkaye.id)
comment75 = Comment.create!(body: 'adding to my playlist', song_id: song15.id, author_id: the1975.id)

comment76 = Comment.create!(body: 'repeat x100', song_id: song16.id, author_id: aku.id)
comment77 = Comment.create!(body: 'so hype', song_id: song16.id, author_id: maggie.id)
comment78 = Comment.create!(body: 'you`re the best!!', song_id: song16.id, author_id: youngbombs.id)
comment79 = Comment.create!(body: 'so excited for this song', song_id: song16.id, author_id: ss.id)
comment80 = Comment.create!(body: 'please go on tour in Europe', song_id: song16.id, author_id: kygo.id)

comment81 = Comment.create!(body: 'can`t stop listening', song_id: song17.id, author_id: rehab.id)
comment82 = Comment.create!(body: 'blasting this while driving', song_id: song17.id, author_id: aku.id)
comment83 = Comment.create!(body: 'too good', song_id: song17.id, author_id: kygo.id)
comment84 = Comment.create!(body: 'summer vibes', song_id: song17.id, author_id: bkaye.id)
comment85 = Comment.create!(body: 'adding to my playlist', song_id: song17.id, author_id: the1975.id)

comment86 = Comment.create!(body: 'repeat x100', song_id: song18.id, author_id: aku.id)
comment87 = Comment.create!(body: 'so hype', song_id: song18.id, author_id: maggie.id)
comment88 = Comment.create!(body: 'you`re the best!!', song_id: song18.id, author_id: youngbombs.id)
comment89 = Comment.create!(body: 'so excited for this song', song_id: song18.id, author_id: ss.id)
comment90 = Comment.create!(body: 'please go on tour in Europe', song_id: song18.id, author_id: kygo.id)

comment91 = Comment.create!(body: 'can`t stop listening', song_id: song19.id, author_id: rehab.id)
comment92 = Comment.create!(body: 'blasting this while driving', song_id: song19.id, author_id: aku.id)
comment93 = Comment.create!(body: 'too good', song_id: song19.id, author_id: kygo.id)
comment94 = Comment.create!(body: 'summer vibes', song_id: song19.id, author_id: bkaye.id)
comment95 = Comment.create!(body: 'adding to my playlist', song_id: song19.id, author_id: the1975.id)

comment96 = Comment.create!(body: 'repeat x100', song_id: song20.id, author_id: aku.id)
comment97 = Comment.create!(body: 'so hype', song_id: song20.id, author_id: maggie.id)
comment98 = Comment.create!(body: 'you`re the best!!', song_id: song20.id, author_id: youngbombs.id)
comment99 = Comment.create!(body: 'so excited for this song', song_id: song20.id, author_id: ss.id)
comment100 = Comment.create!(body: 'please go on tour in Europe', song_id: song20.id, author_id: kygo.id)

comment101 = Comment.create!(body: 'can`t stop listening', song_id: song21.id, author_id: rehab.id)
comment102 = Comment.create!(body: 'blasting this while driving', song_id: song21.id, author_id: aku.id)
comment103 = Comment.create!(body: 'too good', song_id: song21.id, author_id: kygo.id)
comment104 = Comment.create!(body: 'summer vibes', song_id: song21.id, author_id: bkaye.id)
comment105 = Comment.create!(body: 'adding to my playlist', song_id: song21.id, author_id: the1975.id)

comment106 = Comment.create!(body: 'repeat x100', song_id: song22.id, author_id: aku.id)
comment107 = Comment.create!(body: 'so hype', song_id: song22.id, author_id: maggie.id)
comment108 = Comment.create!(body: 'you`re the best!!', song_id: song22.id, author_id: youngbombs.id)
comment109 = Comment.create!(body: 'so excited for this song', song_id: song22.id, author_id: ss.id)
comment110 = Comment.create!(body: 'please go on tour in Europe', song_id: song22.id, author_id: kygo.id)

comment111 = Comment.create!(body: 'can`t stop listening', song_id: song23.id, author_id: rehab.id)
comment112 = Comment.create!(body: 'blasting this while driving', song_id: song23.id, author_id: aku.id)
comment113 = Comment.create!(body: 'too good', song_id: song23.id, author_id: kygo.id)
comment114 = Comment.create!(body: 'summer vibes', song_id: song23.id, author_id: bkaye.id)
comment115 = Comment.create!(body: 'adding to my playlist', song_id: song23.id, author_id: the1975.id)

comment116 = Comment.create!(body: 'repeat x100', song_id: song24.id, author_id: aku.id)
comment117 = Comment.create!(body: 'so hype', song_id: song24.id, author_id: maggie.id)
comment118 = Comment.create!(body: 'you`re the best!!', song_id: song24.id, author_id: youngbombs.id)
comment119 = Comment.create!(body: 'so excited for this song', song_id: song24.id, author_id: ss.id)
comment120 = Comment.create!(body: 'please go on tour in Europe', song_id: song24.id, author_id: kygo.id)

comment121 = Comment.create!(body: 'can`t stop listening', song_id: song25.id, author_id: rehab.id)
comment122 = Comment.create!(body: 'blasting this while driving', song_id: song25.id, author_id: aku.id)
comment123 = Comment.create!(body: 'too good', song_id: song25.id, author_id: kygo.id)
comment124 = Comment.create!(body: 'summer vibes', song_id: song25.id, author_id: bkaye.id)
comment125 = Comment.create!(body: 'adding to my playlist', song_id: song25.id, author_id: the1975.id)

comment126 = Comment.create!(body: 'repeat x100', song_id: song26.id, author_id: aku.id)
comment127 = Comment.create!(body: 'so hype', song_id: song26.id, author_id: maggie.id)
comment128 = Comment.create!(body: 'you`re the best!!', song_id: song26.id, author_id: youngbombs.id)
comment129 = Comment.create!(body: 'so excited for this song', song_id: song26.id, author_id: ss.id)
comment130 = Comment.create!(body: 'please go on tour in Europe', song_id: song26.id, author_id: kygo.id)

comment131 = Comment.create!(body: 'can`t stop listening', song_id: song27.id, author_id: rehab.id)
comment132 = Comment.create!(body: 'blasting this while driving', song_id: song27.id, author_id: aku.id)
comment133 = Comment.create!(body: 'too good', song_id: song27.id, author_id: kygo.id)
comment134 = Comment.create!(body: 'summer vibes', song_id: song27.id, author_id: bkaye.id)
comment135 = Comment.create!(body: 'adding to my playlist', song_id: song27.id, author_id: the1975.id)

comment136 = Comment.create!(body: 'repeat x100', song_id: song28.id, author_id: aku.id)
comment137 = Comment.create!(body: 'so hype', song_id: song28.id, author_id: maggie.id)
comment138 = Comment.create!(body: 'you`re the best!!', song_id: song28.id, author_id: youngbombs.id)
comment139 = Comment.create!(body: 'so excited for this song', song_id: song28.id, author_id: ss.id)
comment140 = Comment.create!(body: 'please go on tour in Europe', song_id: song28.id, author_id: kygo.id)

comment141 = Comment.create!(body: 'can`t stop listening', song_id: song29.id, author_id: rehab.id)
comment142 = Comment.create!(body: 'blasting this while driving', song_id: song29.id, author_id: aku.id)
comment143 = Comment.create!(body: 'too good', song_id: song29.id, author_id: kygo.id)
comment144 = Comment.create!(body: 'summer vibes', song_id: song29.id, author_id: bkaye.id)
comment145 = Comment.create!(body: 'adding to my playlist', song_id: song29.id, author_id: the1975.id)

comment146 = Comment.create!(body: 'repeat x100', song_id: song30.id, author_id: aku.id)
comment147 = Comment.create!(body: 'so hype', song_id: song30.id, author_id: maggie.id)
comment148 = Comment.create!(body: 'you`re the best!!', song_id: song30.id, author_id: youngbombs.id)
comment149 = Comment.create!(body: 'so excited for this song', song_id: song30.id, author_id: ss.id)
comment150 = Comment.create!(body: 'please go on tour in Europe', song_id: song30.id, author_id: kygo.id)

comment151 = Comment.create!(body: 'can`t stop listening', song_id: song31.id, author_id: rehab.id)
comment152 = Comment.create!(body: 'blasting this while driving', song_id: song31.id, author_id: aku.id)
comment153 = Comment.create!(body: 'too good', song_id: song31.id, author_id: kygo.id)
comment154 = Comment.create!(body: 'summer vibes', song_id: song31.id, author_id: bkaye.id)
comment155 = Comment.create!(body: 'adding to my playlist', song_id: song31.id, author_id: the1975.id)

comment156 = Comment.create!(body: 'repeat x100', song_id: song32.id, author_id: aku.id)
comment157 = Comment.create!(body: 'so hype', song_id: song32.id, author_id: maggie.id)
comment158 = Comment.create!(body: 'you`re the best!!', song_id: song32.id, author_id: youngbombs.id)
comment159 = Comment.create!(body: 'so excited for this song', song_id: song32.id, author_id: ss.id)
comment160 = Comment.create!(body: 'please go on tour in Europe', song_id: song32.id, author_id: kygo.id)

comment161 = Comment.create!(body: 'can`t stop listening', song_id: song33.id, author_id: rehab.id)
comment162 = Comment.create!(body: 'blasting this while driving', song_id: song33.id, author_id: aku.id)
comment163 = Comment.create!(body: 'too good', song_id: song33.id, author_id: kygo.id)
comment164 = Comment.create!(body: 'summer vibes', song_id: song33.id, author_id: bkaye.id)
comment165 = Comment.create!(body: 'adding to my playlist', song_id: song33.id, author_id: the1975.id)

comment166 = Comment.create!(body: 'repeat x100', song_id: song34.id, author_id: aku.id)
comment167 = Comment.create!(body: 'so hype', song_id: song34.id, author_id: maggie.id)
comment168 = Comment.create!(body: 'you`re the best!!', song_id: song34.id, author_id: youngbombs.id)
comment169 = Comment.create!(body: 'so excited for this song', song_id: song34.id, author_id: ss.id)
comment170 = Comment.create!(body: 'please go on tour in Europe', song_id: song34.id, author_id: kygo.id)

comment171 = Comment.create!(body: 'can`t stop listening', song_id: song35.id, author_id: rehab.id)
comment172 = Comment.create!(body: 'blasting this while driving', song_id: song35.id, author_id: aku.id)
comment173 = Comment.create!(body: 'too good', song_id: song35.id, author_id: kygo.id)
comment174 = Comment.create!(body: 'summer vibes', song_id: song35.id, author_id: bkaye.id)
comment175 = Comment.create!(body: 'adding to my playlist', song_id: song35.id, author_id: the1975.id)

comment176 = Comment.create!(body: 'repeat x100', song_id: song36.id, author_id: aku.id)
comment177 = Comment.create!(body: 'so hype', song_id: song36.id, author_id: maggie.id)
comment178 = Comment.create!(body: 'you`re the best!!', song_id: song36.id, author_id: youngbombs.id)
comment179 = Comment.create!(body: 'so excited for this song', song_id: song36.id, author_id: ss.id)
comment180 = Comment.create!(body: 'please go on tour in Europe', song_id: song36.id, author_id: kygo.id)

comment181 = Comment.create!(body: 'can`t stop listening', song_id: song37.id, author_id: rehab.id)
comment182 = Comment.create!(body: 'blasting this while driving', song_id: song37.id, author_id: aku.id)
comment183 = Comment.create!(body: 'too good', song_id: song37.id, author_id: kygo.id)
comment184 = Comment.create!(body: 'summer vibes', song_id: song37.id, author_id: bkaye.id)
comment185 = Comment.create!(body: 'adding to my playlist', song_id: song37.id, author_id: the1975.id)

comment186 = Comment.create!(body: 'repeat x100', song_id: song38.id, author_id: aku.id)
comment187 = Comment.create!(body: 'so hype', song_id: song38.id, author_id: maggie.id)
comment188 = Comment.create!(body: 'you`re the best!!', song_id: song38.id, author_id: youngbombs.id)
comment189 = Comment.create!(body: 'so excited for this song', song_id: song38.id, author_id: ss.id)
comment190 = Comment.create!(body: 'please go on tour in Europe', song_id: song38.id, author_id: kygo.id)

comment191 = Comment.create!(body: 'can`t stop listening', song_id: song39.id, author_id: rehab.id)
comment192 = Comment.create!(body: 'blasting this while driving', song_id: song39.id, author_id: aku.id)
comment193 = Comment.create!(body: 'too good', song_id: song39.id, author_id: kygo.id)
comment194 = Comment.create!(body: 'summer vibes', song_id: song39.id, author_id: bkaye.id)
comment195 = Comment.create!(body: 'adding to my playlist', song_id: song39.id, author_id: the1975.id)

comment196 = Comment.create!(body: 'repeat x100', song_id: song40.id, author_id: aku.id)
comment197 = Comment.create!(body: 'so hype', song_id: song40.id, author_id: maggie.id)
comment198 = Comment.create!(body: 'you`re the best!!', song_id: song40.id, author_id: youngbombs.id)
comment199 = Comment.create!(body: 'so excited for this song', song_id: song40.id, author_id: ss.id)
comment200 = Comment.create!(body: 'please go on tour in Europe', song_id: song40.id, author_id: kygo.id)

comment201 = Comment.create!(body: 'can`t stop listening', song_id: song41.id, author_id: rehab.id)
comment202 = Comment.create!(body: 'blasting this while driving', song_id: song41.id, author_id: aku.id)
comment203 = Comment.create!(body: 'too good', song_id: song41.id, author_id: kygo.id)
comment204 = Comment.create!(body: 'summer vibes', song_id: song41.id, author_id: bkaye.id)
comment205 = Comment.create!(body: 'adding to my playlist', song_id: song41.id, author_id: the1975.id)

comment206 = Comment.create!(body: 'repeat x100', song_id: song42.id, author_id: aku.id)
comment207 = Comment.create!(body: 'so hype', song_id: song42.id, author_id: maggie.id)
comment208 = Comment.create!(body: 'you`re the best!!', song_id: song42.id, author_id: youngbombs.id)
comment209 = Comment.create!(body: 'so excited for this song', song_id: song42.id, author_id: ss.id)
comment210 = Comment.create!(body: 'please go on tour in Europe', song_id: song42.id, author_id: kygo.id)

comment211 = Comment.create!(body: 'can`t stop listening', song_id: song43.id, author_id: rehab.id)
comment212 = Comment.create!(body: 'blasting this while driving', song_id: song43.id, author_id: aku.id)
comment213 = Comment.create!(body: 'too good', song_id: song43.id, author_id: kygo.id)
comment214 = Comment.create!(body: 'summer vibes', song_id: song43.id, author_id: bkaye.id)
comment215 = Comment.create!(body: 'adding to my playlist', song_id: song43.id, author_id: the1975.id)

comment216 = Comment.create!(body: 'repeat x100', song_id: song44.id, author_id: aku.id)
comment217 = Comment.create!(body: 'so hype', song_id: song44.id, author_id: maggie.id)
comment218 = Comment.create!(body: 'you`re the best!!', song_id: song44.id, author_id: youngbombs.id)
comment219 = Comment.create!(body: 'so excited for this song', song_id: song44.id, author_id: ss.id)
comment220 = Comment.create!(body: 'please go on tour in Europe', song_id: song44.id, author_id: kygo.id)

comment221 = Comment.create!(body: 'can`t stop listening', song_id: song45.id, author_id: rehab.id)
comment222 = Comment.create!(body: 'blasting this while driving', song_id: song45.id, author_id: aku.id)
comment223 = Comment.create!(body: 'too good', song_id: song45.id, author_id: kygo.id)
comment224 = Comment.create!(body: 'summer vibes', song_id: song45.id, author_id: bkaye.id)
comment225 = Comment.create!(body: 'adding to my playlist', song_id: song45.id, author_id: the1975.id)

comment226 = Comment.create!(body: 'repeat x100', song_id: song46.id, author_id: aku.id)
comment227 = Comment.create!(body: 'so hype', song_id: song46.id, author_id: maggie.id)
comment228 = Comment.create!(body: 'you`re the best!!', song_id: song46.id, author_id: youngbombs.id)
comment229 = Comment.create!(body: 'so excited for this song', song_id: song46.id, author_id: ss.id)
comment230 = Comment.create!(body: 'please go on tour in Europe', song_id: song46.id, author_id: kygo.id)

comment231 = Comment.create!(body: 'can`t stop listening', song_id: song47.id, author_id: rehab.id)
comment232 = Comment.create!(body: 'blasting this while driving', song_id: song47.id, author_id: aku.id)
comment233 = Comment.create!(body: 'too good', song_id: song47.id, author_id: kygo.id)
comment234 = Comment.create!(body: 'summer vibes', song_id: song47.id, author_id: bkaye.id)
comment235 = Comment.create!(body: 'adding to my playlist', song_id: song47.id, author_id: the1975.id)

comment236 = Comment.create!(body: 'repeat x100', song_id: song48.id, author_id: aku.id)
comment237 = Comment.create!(body: 'so hype', song_id: song48.id, author_id: maggie.id)
comment238 = Comment.create!(body: 'you`re the best!!', song_id: song48.id, author_id: youngbombs.id)
comment239 = Comment.create!(body: 'so excited for this song', song_id: song48.id, author_id: ss.id)
comment240 = Comment.create!(body: 'please go on tour in Europe', song_id: song48.id, author_id: kygo.id)

comment241 = Comment.create!(body: 'can`t stop listening', song_id: song49.id, author_id: rehab.id)
comment242 = Comment.create!(body: 'blasting this while driving', song_id: song49.id, author_id: aku.id)
comment243 = Comment.create!(body: 'too good', song_id: song49.id, author_id: kygo.id)
comment244 = Comment.create!(body: 'summer vibes', song_id: song49.id, author_id: bkaye.id)
comment245 = Comment.create!(body: 'adding to my playlist', song_id: song49.id, author_id: the1975.id)

comment246 = Comment.create!(body: 'repeat x100', song_id: song50.id, author_id: aku.id)
comment247 = Comment.create!(body: 'so hype', song_id: song50.id, author_id: maggie.id)
comment248 = Comment.create!(body: 'you`re the best!!', song_id: song50.id, author_id: youngbombs.id)
comment249 = Comment.create!(body: 'so excited for this song', song_id: song50.id, author_id: ss.id)
comment250 = Comment.create!(body: 'please go on tour in Europe', song_id: song50.id, author_id: kygo.id)

comment251 = Comment.create!(body: 'can`t stop listening', song_id: song51.id, author_id: rehab.id)
comment252 = Comment.create!(body: 'blasting this while driving', song_id: song51.id, author_id: aku.id)
comment253 = Comment.create!(body: 'too good', song_id: song51.id, author_id: kygo.id)
comment254 = Comment.create!(body: 'summer vibes', song_id: song51.id, author_id: bkaye.id)
comment255 = Comment.create!(body: 'adding to my playlist', song_id: song51.id, author_id: the1975.id)

comment256 = Comment.create!(body: 'repeat x100', song_id: song52.id, author_id: aku.id)
comment257 = Comment.create!(body: 'so hype', song_id: song52.id, author_id: maggie.id)
comment258 = Comment.create!(body: 'you`re the best!!', song_id: song52.id, author_id: youngbombs.id)
comment259 = Comment.create!(body: 'so excited for this song', song_id: song52.id, author_id: ss.id)
comment260 = Comment.create!(body: 'please go on tour in Europe', song_id: song52.id, author_id: kygo.id)

comment261 = Comment.create!(body: 'can`t stop listening', song_id: song53.id, author_id: rehab.id)
comment262 = Comment.create!(body: 'blasting this while driving', song_id: song53.id, author_id: aku.id)
comment263 = Comment.create!(body: 'too good', song_id: song53.id, author_id: kygo.id)
comment264 = Comment.create!(body: 'summer vibes', song_id: song53.id, author_id: bkaye.id)
comment265 = Comment.create!(body: 'adding to my playlist', song_id: song53.id, author_id: the1975.id)

comment266 = Comment.create!(body: 'repeat x100', song_id: song54.id, author_id: aku.id)
comment267 = Comment.create!(body: 'so hype', song_id: song54.id, author_id: maggie.id)
comment268 = Comment.create!(body: 'you`re the best!!', song_id: song54.id, author_id: youngbombs.id)
comment269 = Comment.create!(body: 'so excited for this song', song_id: song54.id, author_id: ss.id)
comment270 = Comment.create!(body: 'please go on tour in Europe', song_id: song54.id, author_id: kygo.id)

comment271 = Comment.create!(body: 'can`t stop listening', song_id: song55.id, author_id: rehab.id)
comment272 = Comment.create!(body: 'blasting this while driving', song_id: song55.id, author_id: aku.id)
comment273 = Comment.create!(body: 'too good', song_id: song55.id, author_id: kygo.id)
comment274 = Comment.create!(body: 'summer vibes', song_id: song55.id, author_id: bkaye.id)
comment275 = Comment.create!(body: 'adding to my playlist', song_id: song55.id, author_id: the1975.id)

comment276 = Comment.create!(body: 'repeat x100', song_id: song56.id, author_id: aku.id)
comment277 = Comment.create!(body: 'so hype', song_id: song56.id, author_id: maggie.id)
comment278 = Comment.create!(body: 'you`re the best!!', song_id: song56.id, author_id: youngbombs.id)
comment279 = Comment.create!(body: 'so excited for this song', song_id: song56.id, author_id: ss.id)
comment280 = Comment.create!(body: 'please go on tour in Europe', song_id: song56.id, author_id: kygo.id)

comment281 = Comment.create!(body: 'can`t stop listening', song_id: song57.id, author_id: rehab.id)
comment282 = Comment.create!(body: 'blasting this while driving', song_id: song57.id, author_id: aku.id)
comment283 = Comment.create!(body: 'too good', song_id: song57.id, author_id: kygo.id)
comment284 = Comment.create!(body: 'summer vibes', song_id: song57.id, author_id: bkaye.id)
comment285 = Comment.create!(body: 'adding to my playlist', song_id: song57.id, author_id: the1975.id)

comment286 = Comment.create!(body: 'repeat x100', song_id: song58.id, author_id: aku.id)
comment287 = Comment.create!(body: 'so hype', song_id: song58.id, author_id: maggie.id)
comment288 = Comment.create!(body: 'you`re the best!!', song_id: song58.id, author_id: youngbombs.id)
comment289 = Comment.create!(body: 'so excited for this song', song_id: song58.id, author_id: ss.id)
comment290 = Comment.create!(body: 'please go on tour in Europe', song_id: song58.id, author_id: kygo.id)

comment291 = Comment.create!(body: 'can`t stop listening', song_id: song59.id, author_id: rehab.id)
comment292 = Comment.create!(body: 'blasting this while driving', song_id: song59.id, author_id: aku.id)
comment293 = Comment.create!(body: 'too good', song_id: song59.id, author_id: kygo.id)
comment294 = Comment.create!(body: 'summer vibes', song_id: song59.id, author_id: bkaye.id)
comment295 = Comment.create!(body: 'adding to my playlist', song_id: song59.id, author_id: the1975.id)

comment296 = Comment.create!(body: 'repeat x100', song_id: song60.id, author_id: aku.id)
comment297 = Comment.create!(body: 'so hype', song_id: song60.id, author_id: maggie.id)
comment298 = Comment.create!(body: 'you`re the best!!', song_id: song60.id, author_id: youngbombs.id)
comment299 = Comment.create!(body: 'so excited for this song', song_id: song60.id, author_id: ss.id)
comment300 = Comment.create!(body: 'please go on tour in Europe', song_id: song60.id, author_id: kygo.id)

comment301 = Comment.create!(body: 'can`t stop listening', song_id: song61.id, author_id: rehab.id)
comment302 = Comment.create!(body: 'blasting this while driving', song_id: song61.id, author_id: aku.id)
comment303 = Comment.create!(body: 'too good', song_id: song61.id, author_id: kygo.id)
comment304 = Comment.create!(body: 'summer vibes', song_id: song61.id, author_id: bkaye.id)
comment305 = Comment.create!(body: 'adding to my playlist', song_id: song61.id, author_id: the1975.id)

comment306 = Comment.create!(body: 'repeat x100', song_id: song62.id, author_id: aku.id)
comment307 = Comment.create!(body: 'so hype', song_id: song62.id, author_id: maggie.id)
comment308 = Comment.create!(body: 'you`re the best!!', song_id: song62.id, author_id: youngbombs.id)
comment309 = Comment.create!(body: 'so excited for this song', song_id: song62.id, author_id: ss.id)
comment310 = Comment.create!(body: 'please go on tour in Europe', song_id: song62.id, author_id: kygo.id)

comment311 = Comment.create!(body: 'can`t stop listening', song_id: song63.id, author_id: rehab.id)
comment312 = Comment.create!(body: 'blasting this while driving', song_id: song63.id, author_id: aku.id)
comment313 = Comment.create!(body: 'too good', song_id: song63.id, author_id: kygo.id)
comment314 = Comment.create!(body: 'summer vibes', song_id: song63.id, author_id: bkaye.id)
comment315 = Comment.create!(body: 'adding to my playlist', song_id: song63.id, author_id: the1975.id)
